sudo: false
dist: xenial   # required for Python >= 3.7
language: python
python:
  - 2.7
  - 3.6

before_install:
  - pip install tox
  - pip install codecov

script:
  - if [[ $TRAVIS_PYTHON_VERSION == 3.6 ]]; then tox -e py36,lint; fi
  - if [[ $TRAVIS_PYTHON_VERSION == 2.7 ]]; then tox -e py27; fi
  - if [[ $TRAVIS_PYTHON_VERSION == 3.7 ]]; then tox -e py37; fi

after_success:
  - codecov

branches:
  only:
    - master
    - /^v\d+\.\d+\.\d+(-\S+)?$/

deploy:
  provider: pypi
  on:
    tags: true
    branch: master
    skip_existing: true
  user: bbp.opensource
  password:
    secure: Wd7WpmYKtg8KBMx0B8Rpt0K47XSoPMPumqE1o5g7RmRfcJSlbt7zdxsFnT8FsIQEVXkr38Pe5jnCWVWfUw8eWs5GpsiLwHx0cBrp079QtBlK3bw8vPg4xxsTge2nIWczk/ZLg/uiUBocAnusF487AdJ7/vniZCHu1tDiP8CHV5E7EHb9NAQacG21SB/YGRzob2Cru4/ABk/CdPOVMEP3KvMX4bN7dHb0hwi/KUqqQRcbAyfpNV6IW/7Id6aUjBZgusM5xApYhM9SHloigp/CEeOY3axFlpQcOQT1LWbp+g+7I+fYrVwv2sO7EoMTVuwog14wstTJlJ9AebmW80XoUrycwQCVZs8WIF/0YYn9QuypoGyxNyLrKfGJugPgRur4MLS4RIgoL248LVOkM+ZfHELO2Vpw6Ekj94R1Lk0Wir7IGhnj83kUyHfzOyBo5ugMRopKxEGAXysSE+I8e8ua71yu7IBWIWbOKAZPdg6H3I8B257iO25eOMJj47pXVpe+VArpC5JnVjQLDViyh4dcg/XdBjHzq02erPguwRBnRdlXoueswPD2AtI4VRKKWJI+Q87ocOIrLaxmVtlFPFI4Y+XRAmAHTzWCy9WGVrE6//HPr2jb225Y0SUV6qMTVFu1ib8fPZe66AKHdldiVYI37H5PWIrqEVXSS2+uMFzVNlw=
